# Generated by Django 3.1.4 on 2020-12-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201226_2006'),
        ('jobs', '0004_auto_20201226_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
